name: bytebeam_assessment
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  path_provider: ^2.1.6
  get_it: ^9.2.1
  injectable: ^3.0.0
  go_router: 17.5.0
  path: ^1.9.1
  dart_duckdb: 1.2.0
  freezed_annotation: ^3.1.0
  equatable: ^2.1.0
  fpdart: ^1.2.0
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^3.1.3
  build_runner: ^2.15.1
  freezed: ^4.0.0-dev.3

flutter:
  generate: true
  uses-material-design: true